name: Build iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Download Godot
      run: |
        curl -L -o godot.zip "https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_macos.universal.zip"
        unzip godot.zip
        ls -la
        
    - name: Export
      run: |
        ls Godot_v4.4-stable_macos.universal/
